# Generated by Django 5.2.7 on 2025-10-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0001_initial'),
        ('forum', '0002_remove_post_club_post_clubs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='clubs',
        ),
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Tag a club (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='club_directories.club'),
        ),
    ]
