# Generated by Django 5.2.7 on 2025-10-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0001_initial'),
        ('forum', '0003_remove_post_clubs_post_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='club',
        ),
        migrations.AddField(
            model_name='post',
            name='clubs',
            field=models.ManyToManyField(blank=True, help_text='Tag clubs (can select multiple)', related_name='tagged_posts', to='club_directories.club'),
        ),
    ]
