# Generated by Django 5.2.7 on 2025-10-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='fifa_ranking',
        ),
        migrations.RemoveField(
            model_name='club',
            name='stadium',
        ),
    ]
