# Generated by Django 5.2.7 on 2025-10-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDetails',
            fields=[
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='club_directories.club')),
                ('description', models.TextField(blank=True, null=True)),
                ('history_summary', models.TextField(blank=True, null=True)),
                ('stadium_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stadium_capacity', models.IntegerField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
