# Generated by Django 5.2.7 on 2025-10-25 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0003_clubdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_in_leagues', to='club_directories.club')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_for_league', to='club_directories.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
        migrations.DeleteModel(
            name='FavoriteClub',
        ),
    ]
