# Generated by Django 5.2.7 on 2025-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profpict',
            field=models.URLField(blank=True, null=True),
        ),
    ]
