# Generated by Django 5.2.7 on 2025-12-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_profpict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profpict',
        ),
    ]
