# Generated by Django 5.2.7 on 2025-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_profpict'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profpict',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
