# Generated by Django 5.2.5 on 2025-10-22 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('stadium', models.CharField(blank=True, max_length=200)),
                ('fifa_ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=3)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in meters', max_digits=4, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Market value in millions', max_digits=12, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='statisticsrafi.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('POTY', 'Player of the Year'), ('POTM', 'Player of the Month'), ('POTW', 'Player of the Week'), ('GOLDEN_BOOT', 'Golden Boot'), ('GOLDEN_GLOVE', 'Golden Glove'), ('TEAM_OTY', 'Team of the Year'), ('TEAM_POTM', 'Team of the Month'), ('TEAM_POTW', 'Team of the Week'), ('OTHER', 'Other Award')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=10)),
                ('date_awarded', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='statisticsrafi.club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='statisticsrafi.player')),
            ],
            options={
                'ordering': ['-date_awarded'],
            },
        ),
        migrations.CreateModel(
            name='PlayerComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('compared_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_player1', to='statisticsrafi.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_player2', to='statisticsrafi.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-compared_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('continent', models.CharField(max_length=50)),
                ('ranking_date', models.DateField()),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='statisticsrafi.club')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('club', 'ranking_date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26')], max_length=10)),
                ('appearances', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutes_played', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('assists', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shots_on_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clean_sheets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tackles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('interceptions', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('yellow_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('red_cards', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsrafi.player')),
            ],
            options={
                'verbose_name_plural': 'Player Statistics',
                'ordering': ['-season', '-goals'],
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='statisticsrafi.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
                'unique_together': {('user', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PLAYER_WEEK', 'Player of the Week'), ('PLAYER_MONTH', 'Player of the Month'), ('PLAYER_SEASON', 'Player of the Season'), ('TEAM_WEEK', 'Team of the Week'), ('TEAM_MONTH', 'Team of the Month'), ('TEAM_SEASON', 'Team of the Season')], max_length=20)),
                ('season', models.CharField(max_length=10)),
                ('week_number', models.IntegerField(blank=True, help_text='Week number for weekly votes', null=True)),
                ('month_number', models.IntegerField(blank=True, help_text='Month number for monthly votes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='statisticsrafi.club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='statisticsrafi.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('user', 'category', 'season', 'week_number', 'month_number')},
            },
        ),
    ]
