# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('club_directories', '0001_initial'),
        ('statisticsrafi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2025/26', max_length=10)),
                ('wins', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('draws', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xg_for_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Expected Goals For per Match', max_digits=5, null=True)),
                ('xg_against_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Expected Goals Against per Match', max_digits=5, null=True)),
                ('scored_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Goals Scored per Match', max_digits=5, null=True)),
                ('conceded_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Goals Conceded per Match', max_digits=5, null=True)),
                ('avg_match_goals', models.DecimalField(blank=True, decimal_places=2, help_text='Average Match Goals', max_digits=5, null=True)),
                ('clean_sheets_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Clean Sheets %', max_digits=5, null=True)),
                ('failed_to_score_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Failed to Score %', max_digits=5, null=True)),
                ('possession_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average Possession %', max_digits=5, null=True)),
                ('shots_taken_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Shots Taken per Match', max_digits=5, null=True)),
                ('shots_conversion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Shots Conversion Rate %', max_digits=5, null=True)),
                ('fouls_committed_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Fouls Committed per Match', max_digits=5, null=True)),
                ('fouled_against_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Fouled Against per Match', max_digits=5, null=True)),
                ('penalties_won', models.CharField(blank=True, help_text="Penalties Won (e.g., '2 in 8')", max_length=20)),
                ('penalties_conceded', models.CharField(blank=True, help_text="Penalties Conceded (e.g., '0 in 8')", max_length=20)),
                ('goal_kicks_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Goal Kicks per Match', max_digits=5, null=True)),
                ('throw_ins_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Throw-ins per Match', max_digits=5, null=True)),
                ('free_kicks_per_match', models.DecimalField(blank=True, decimal_places=2, help_text='Free-Kicks per Match', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='club_directories.club')),
            ],
            options={
                'verbose_name_plural': 'Team Statistics',
                'ordering': ['-season', 'club__name'],
                'unique_together': {('club', 'season')},
            },
        ),
    ]
