# Generated by Django 5.2.7 on 2025-10-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsrafi', '0003_clubvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubvote',
            name='season',
            field=models.CharField(choices=[('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26')], default='2025/26', max_length=10),
        ),
    ]
