# Generated by Django 5.2.5 on 2025-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsrafi', '0004_alter_clubvote_season'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update the Django state
                migrations.DeleteModel(name='PlayerStatistics'),
                migrations.DeleteModel(name='PlayerComparison'),
                migrations.DeleteModel(name='UserWatchlist'),
                migrations.DeleteModel(name='Player'),
                migrations.RemoveField(model_name='award', name='player'),
                migrations.RemoveField(model_name='vote', name='player'),
                migrations.AlterField(
                    model_name='award',
                    name='award_type',
                    field=models.CharField(choices=[('TEAM_OTY', 'Team of the Year'), ('TEAM_POTM', 'Team of the Month'), ('TEAM_POTW', 'Team of the Week'), ('OTHER', 'Other Award')], max_length=20),
                ),
                migrations.AlterField(
                    model_name='vote',
                    name='category',
                    field=models.CharField(choices=[('TEAM_WEEK', 'Team of the Week'), ('TEAM_MONTH', 'Team of the Month'), ('TEAM_SEASON', 'Team of the Season')], max_length=20),
                ),
            ],
            database_operations=[
                # Drop the tables in the database
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS statisticsrafi_playerstatistics;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS statisticsrafi_playercomparison;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS statisticsrafi_userwatchlist;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS statisticsrafi_player;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Recreate Award table without player field
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE statisticsrafi_award_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        award_type VARCHAR(20) NOT NULL,
                        title VARCHAR(200) NOT NULL,
                        season VARCHAR(10) NOT NULL,
                        date_awarded DATE NOT NULL,
                        description TEXT NOT NULL,
                        club_id CHAR(32) NULL REFERENCES club_directories_club(id) ON DELETE CASCADE
                    );
                    INSERT INTO statisticsrafi_award_new (id, award_type, title, season, date_awarded, description, club_id)
                    SELECT id, award_type, title, season, date_awarded, description, club_id
                    FROM statisticsrafi_award;
                    DROP TABLE statisticsrafi_award;
                    ALTER TABLE statisticsrafi_award_new RENAME TO statisticsrafi_award;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # Recreate Vote table without player field
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE statisticsrafi_vote_new (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        category VARCHAR(20) NOT NULL,
                        season VARCHAR(10) NOT NULL,
                        week_number INTEGER NULL,
                        month_number INTEGER NULL,
                        voted_at DATETIME NOT NULL,
                        user_id INTEGER NOT NULL REFERENCES main_customuser(id) ON DELETE CASCADE,
                        club_id CHAR(32) NULL REFERENCES club_directories_club(id) ON DELETE CASCADE,
                        UNIQUE (user_id, category, season, week_number, month_number)
                    );
                    INSERT INTO statisticsrafi_vote_new (id, category, season, week_number, month_number, voted_at, user_id, club_id)
                    SELECT id, category, season, week_number, month_number, voted_at, user_id, club_id
                    FROM statisticsrafi_vote;
                    DROP TABLE statisticsrafi_vote;
                    ALTER TABLE statisticsrafi_vote_new RENAME TO statisticsrafi_vote;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
